### ISSUE TITLE
[BUG] docs link is broken

### ISSUE THREAD

**Issue by gingerkidney** [taichi-dev/taichi-zoo-issue-tracker#6]
**Describe the bug**
The docs link on the website is broken. 

**To Reproduce**
1. Go to zoo.taichi.graphics
2. Click on docs and it shows page no found

**Expected behavior**
It should be directed to https://docs.taichi.graphics/ I think.

**Screenshots**
![WechatIMG6](https://user-images.githubusercontent.com/29295553/159111686-d6947551-7a3e-4435-93f6-4dae8919fcc5.png)

<img width="1079" alt="截屏2022-03-19 下午3 15 48" src="https://user-images.githubusercontent.com/29295553/159111699-e3b17d8e-131e-454d-9c54-402e8880e9dc.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rexwangcc** [comment]
Thanks for reporting it, it shall be fixed now 😄
